version: 2

.job_template: &job_template
  machine:
    enabled: true
  steps:
    - checkout
    - run:
        command: ./circle-test.sh
    - persist_to_workspace:
        root: .
        paths: [ 'ci-workspace' ]

jobs:
  amd64:
    <<: *job_template
  arm64:
    <<: *job_template
  armhf:
    <<: *job_template
  armel:
    <<: *job_template
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./circle-deploy.sh



workflows:
  version: 2
  build:
    jobs:
      - amd64:
          filters:
            tags:
              only: /^v.*/
      - arm64:
          filters:
            tags:
              only: /^v.*/
      - armhf:
          filters:
            tags:
              only: /^v.*/
      #- armel:
      #    filters:
      #      tags:
      #        only: /^v.*/
      - deploy:
          requires:
            - amd64
            - arm64
            - armhf
            #- armel
          filters:
            tags:
              only: /^v.*/
  nightly_build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: 'beta-v5.0'
    jobs:
      - amd64:
          filters:
            tags:
              only: /^v.*/
      - arm64:
          filters:
            tags:
              only: /^v.*/
      - armhf:
          filters:
            tags:
              only: /^v.*/
      #- armel:
      #    filters:
      #      tags:
      #        only: /^v.*/
      - deploy:
          requires:
            - amd64
            - arm64
            - armhf
            #- armel
          filters:
            tags:
              only: /^v.*/
